### ISSUE TITLE
ansible.builtin.systemd is missing

### ISSUE THREAD

**Issue by jzielke84** [zerwes/ansible-fqcn-converter#22]
The script works fine but seems to skip `systemd`.

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html

**Comment by zerwes** [comment]
Indeed ...
the module is named `systemd_service`, this will work for this.
```yaml
systemd_service:
  - ansible.builtin.systemd_service
```
`ansible.builtin.systemd` is just a redirect to `ansible.builtin.systemd_service` ... see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html

I assume this will happen to all redirects.
I'll have a look on how I can solve this in a generic way.

**Comment by zerwes** [comment]
Hello @jzielke84 
Thank you for the hint! As I already mentioned, I assume this is a general problem.
The error is caused due to the fact that `ansible-doc` reports `systemd_service` as a module name for `systemd`:
```json
{
   "ansible.builtin.systemd" : {
      "doc" : {
         "collection" : "ansible.builtin",
         "module" : "systemd_service",
  }
}
```
I will have a look on how I can fix this, but the result will be that `systemd`will be _fqcn'ed_ to `ansible.builtin.systemd_service`

**Comment by jzielke84** [comment]
Thank you 🙏

**Comment by zerwes** [comment]
fix works as expected:
```diff
+systemd:
+  - ansible.builtin.systemd_service
 systemd_service:
   - ansible.builtin.systemd_service
```

**Comment by zerwes** [comment]
I will rebuild the fqcn map first on `main` and the rebase the feature/fix branch before merging in order to make the diff more eloquent.
So please be patient, fixed release is on the way ... just takes some time (as I try to enjoy the last sunny days before the cold and grey will catch us) ...

**Comment by zerwes** [comment]
Hello @jzielke84 : release 0.4.0 is out incl. the fix for this issue
Thank you for your attention && greetings

**Comment by jzielke84** [comment]
Thank you very much for the quick fix 😃
