### ISSUE TITLE
`ansible-lint --fix` can do the same as this tool?

### ISSUE THREAD

**Issue by ypid** [zerwes/ansible-fqcn-converter#26]
ansible-lint has a handle little option currently called `--fix` that also does this. I guess it did not exist back when you started working on this. Not sure. It was previously called `--write`.

**Comment by zerwes** [comment]
Hello @ypid 
Thank you for the hint.
AFAIR the _write/fix_ feature in ansible-lint appeared somewhere in 2023, the auto-fix for fqdn came with 6.15.0 @ Apr 21, 2023 regarding the changelog
I started this in Aug 2022, so at that time there was no other solution known to me.

For the sake of completeness you are welcome to open a PR that will mention the feature against the `README.md` file, so maybe somebody will prefer that way, especially as it will not require the installation of a additional package.

and btw:
I did not test it extensively, but it seems to me that even with `--fix=fqcn` ansible-lint will fix other stuff too ...
